files:
  - source: /suite/drive/locale/main.pot
    translation: /suite/drive/locale/%two_letters_code%.po
  - source: /suite/mail/locale/main.pot
    translation: /suite/mail/locale/%two_letters_code%.po
pull_request_title: "chore: sync translations from crowdin"
pull_request_labels:
  - translation
commit_message: "chore: %language% translations"
append_commit_message: false
