import { resolve } from "node:path";
import { expect, test } from "../../fixtures/test";
import {
	createWriterDocument,
	openWriterDocument,
	uniqueWriterTitle,
	writerEditor,
} from "../../helpers/writer";
import type { Page } from "@playwright/test";

// Generated by frontend/frappe-ui's own "docx" package: one heading, one
// paragraph, and a 2-row table with the first row flagged as a header.
const fixturePath = resolve(__dirname, "fixtures/import-sample.docx");

async function importDocx(page: Page) {
	const [fileChooser] = await Promise.all([
		page.waitForEvent("filechooser"),
		(async () => {
			await page.getByRole("button", { name: "Document actions" }).click();
			await page.getByRole("menuitem", { name: "Import" }).hover();
			await page.getByRole("menuitem", { name: "DOCX" }).click();
		})(),
	]);
	await fileChooser.setFiles(fixturePath);
}

test("imports a .docx into an empty document", async ({ owner, run }) => {
	const title = uniqueWriterTitle(run.run_id, "docx-import-empty");
	const file = await createWriterDocument(owner.page.request, title);
	await openWriterDocument(owner.page, file.name);

	await importDocx(owner.page);

	const editor = writerEditor(owner.page);
	await expect(editor).toContainText("E2E DOCX Import Fixture");
	await expect(editor).toContainText("This paragraph was imported from a .docx file.");
	await expect(editor.locator("table")).toBeVisible();
	await expect(editor.locator("th", { hasText: "Fruit" })).toBeVisible();
	await expect(editor.locator("td", { hasText: "Apple" })).toBeVisible();
	// Only the first row is a header, matching a manually created table.
	await expect(editor.locator("th")).toHaveCount(2);
});

test("imports a .docx into a new tab, leaving existing content untouched", async ({
	owner,
	run,
}) => {
	const title = uniqueWriterTitle(run.run_id, "docx-import-tab");
	const file = await createWriterDocument(owner.page.request, title);
	// The tab switcher lives in the desktop Table of Contents panel.
	await owner.page.addInitScript(() => window.localStorage.setItem("showToc", "true"));
	await openWriterDocument(owner.page, file.name);

	const editor = writerEditor(owner.page);
	await editor.click();
	await owner.page.keyboard.type("Existing content before import");

	await importDocx(owner.page);

	// Importing wraps the existing content into its own ("Untitled") tab and
	// switches to a new tab named after the file for the imported content.
	// Inactive tabs stay mounted (display: none) rather than being removed
	// from the DOM — see TabView.vue — so assertions must scope to the
	// visible tab; toContainText matches hidden text too, unlike innerText.
	const tocTabs = owner.page.locator('[draggable="true"]');
	await expect(tocTabs).toHaveCount(2);
	const activeTab = editor.locator("[data-tab-id]:visible");
	await expect(activeTab).toContainText("E2E DOCX Import Fixture");

	await tocTabs.filter({ hasText: "Untitled" }).click();
	await expect(activeTab).toContainText("Existing content before import");
	await expect(activeTab).not.toContainText("E2E DOCX Import Fixture");
});
