"""Reviewed Persian translations for every literal runtime key in Suite Mail."""

PERSIAN_MAIL_OVERRIDES = {
    "Communications": "ارتباطات",
    "Email Accounts": "حساب‌های ایمیل",
    "Email Queue": "صف ایمیل",
    "Email Templates": "الگوهای ایمیل",
    "Frappe Email": "ایمیل فراپه",
    "Unhandled Email": "ایمیل‌های پردازش‌نشده",
    "(Message deleted)": "(پیام حذف شد)",
    "(No subject)": "(بدون موضوع)",
    ". You won't receive new messages from this source until you unblock them.": ". تا زمانی که این منبع را از مسدودی خارج نکنید، پیام جدیدی از آن دریافت نخواهید کرد.",
    "1 item selected": "۱ مورد انتخاب شد",
    "1 member": "۱ عضو",
    "1 new message": "۱ پیام جدید",
    "1 new sender": "۱ فرستنده جدید",
    "1 new thread": "۱ گفت‌وگوی جدید",
    "1 recipient": "۱ گیرنده",
    "1 redirect URI": "۱ URI تغییر مسیر",
    "1 remote image hidden to protect your privacy.": "برای حفظ حریم خصوصی شما، ۱ تصویر خارجی پنهان شد.",
    "1 result": "۱ نتیجه",
    "[No Subject]": "[بدون موضوع]",
    "[No subject]": "[بدون موضوع]",
    "a sender and their emails go to your Inbox — now and in the future.": "یک فرستنده را مجاز کنید تا ایمیل‌های فعلی و آینده‌اش به صندوق ورودی شما بروند.",
    "a sender once and their emails reach your Inbox from then on;": "یک فرستنده را یک‌بار مجاز کنید تا از آن پس ایمیل‌هایش به صندوق ورودی شما برسند؛",
    "Account updated.": "حساب به‌روزرسانی شد.",
    "Action completed.": "عملیات انجام شد.",
    "Action failed.": "عملیات ناموفق بود.",
    "Action failed. Please try again later.": "عملیات ناموفق بود. لطفاً بعداً دوباره تلاش کنید.",
    "Action updated.": "عملیات به‌روزرسانی شد.",
    "activate": "فعال کردن",
    "Activate Script": "فعال‌سازی اسکریپت",
    "Activate this script to apply your rules and filters.": "برای اعمال قوانین و فیلترهایتان، این اسکریپت را فعال کنید.",
    "activated": "فعال شد",
    "Activating": "در حال فعال‌سازی",
    "Activating this script will deactivate the currently active script.": "با فعال‌سازی این اسکریپت، اسکریپت فعال فعلی غیرفعال می‌شود.",
    "Activating this script will disable {0}.": "با فعال‌سازی این اسکریپت، {0} غیرفعال می‌شود.",
    "Active Script {0} Detected": "اسکریپت فعال {0} شناسایی شد",
    "Add a domain": "افزودن دامنه",
    "Add a domain to send and receive mail with your own addresses.": "دامنه‌ای اضافه کنید تا با نشانی‌های خودتان ایمیل ارسال و دریافت کنید.",
    "Add Address": "افزودن نشانی",
    "Add Address Book": "افزودن دفترچه نشانی",
    "Add another": "افزودن مورد دیگر",
    "Add another email": "افزودن ایمیل دیگر",
    "Add Bcc": "افزودن Bcc",
    "Add Contacts": "افزودن مخاطبان",
    "Add Domain": "افزودن دامنه",
    "Add Email": "افزودن ایمیل",
    "Add Email Address": "افزودن نشانی ایمیل",
    "Add Group": "افزودن گروه",
    "Add Mailing List": "افزودن فهرست پستی",
    "Add Member": "افزودن عضو",
    "Add Members": "افزودن اعضا",
    "Add OAuth Client": "افزودن سرویس‌گیرنده OAuth",
    "Add Phone": "افزودن تلفن",
    "Add Recipients": "افزودن گیرندگان",
    "Add Redirect URIs": "افزودن URIهای تغییر مسیر",
    "Add Reply To": "افزودن نشانی پاسخ",
    "Add Role": "افزودن نقش",
    "Add Star": "ستاره‌دار کردن",
    "Add the following records to your domain's DNS settings.": "رکوردهای زیر را به تنظیمات DNS دامنه خود اضافه کنید.",
    "Add To": "افزودن به",
    "Add to Address Book": "افزودن به دفترچه نشانی",
    "Add to Calendar": "افزودن به تقویم",
    "Add to Groups": "افزودن به گروه‌ها",
    "Add to Mailing Lists": "افزودن به فهرست‌های پستی",
    "Added to groups.": "به گروه‌ها افزوده شد.",
    "Added to mailing lists.": "به فهرست‌های پستی افزوده شد.",
    "Added {0}": "{0} افزوده شد",
    "Address Book": "دفترچه نشانی",
    "Address book created.": "دفترچه نشانی ایجاد شد.",
    "Address book deleted.": "دفترچه نشانی حذف شد.",
    "Address book updated.": "دفترچه نشانی به‌روزرسانی شد.",
    "Admin": "مدیر",
    "Admin Dashboard": "پیشخوان مدیریت",
    "After adding, copy the generated DNS records to your DNS provider.": "پس از افزودن، رکوردهای DNS ایجادشده را در سرویس‌دهنده DNS خود کپی کنید.",
    "Agent User ID": "شناسه کاربری عامل",
    "Algorithm": "الگوریتم",
    "Alias": "نام مستعار",
    "Aliases": "نام‌های مستعار",
    "All Contacts": "همه مخاطبان",
    "All folders": "همه پوشه‌ها",
    "All identities": "همه هویت‌ها",
    "All Mails": "همه ایمیل‌ها",
    "All matching messages cancelled.": "همه پیام‌های منطبق لغو شدند.",
    "All matching messages scheduled for retry.": "تلاش مجدد برای همه پیام‌های منطبق زمان‌بندی شد.",
    "All my work-related contacts": "همه مخاطبان کاری من",
    "All rules and filters associated with this script will stop functioning immediately.": "همه قوانین و فیلترهای مرتبط با این اسکریپت فوراً از کار می‌افتند.",
    "All rules and filters associated with this script will take effect immediately.": "همه قوانین و فیلترهای مرتبط با این اسکریپت فوراً اعمال می‌شوند.",
    "Allow ({0})": "مجاز کردن ({0})",
    "Allow All": "مجاز کردن همه",
    "Allow all emails from {0}": "مجاز کردن همه ایمیل‌های ارسالی از {0}",
    "Allow All Senders": "مجاز کردن همه فرستندگان",
    "Allow and Archive": "مجاز کردن و بایگانی",
    "Allow and Archive ({0})": "مجاز کردن و بایگانی ({0})",
    "Allow and Move to Trash": "مجاز کردن و انتقال به زباله‌دان",
    "Allow and Move to Trash ({0})": "مجاز کردن و انتقال به زباله‌دان ({0})",
    "Allow popups to open attachments.": "برای باز کردن پیوست‌ها، پنجره‌های بازشو را مجاز کنید.",
    "Allow Sender": "مجاز کردن فرستنده",
    "Allow Sender, Archive Their Mail": "مجاز کردن فرستنده و بایگانی ایمیل‌های او",
    "Allow Sender, Trash Their Mail": "مجاز کردن فرستنده و انتقال ایمیل‌های او به زباله‌دان",
    "Already have an account? Log in.": "از قبل حساب دارید؟ وارد شوید.",
    "Amber": "کهربایی",
    "and then \"Add to Home Screen\"": "و سپس «Add to Home Screen»",
    "App Password": "گذرواژه برنامه",
    "Appearance updated.": "ظاهر به‌روزرسانی شد.",
    "Apply filters to select specific contacts for export.": "برای انتخاب مخاطبان خاص جهت برون‌بری، فیلترها را اعمال کنید.",
    "Apply filters to select specific emails for export.": "برای انتخاب ایمیل‌های خاص جهت برون‌بری، فیلترها را اعمال کنید.",
    "Archive (E)": "بایگانی (E)",
    "Archive {0} threads": "بایگانی {0} گفت‌وگو",
    "Are you sure you want to delete '{0}'? ": "مطمئنید می‌خواهید «{0}» را حذف کنید؟ ",
    "Are you sure you want to delete '{0}'? Mails in this folder will be permanently removed.": "مطمئنید می‌خواهید «{0}» را حذف کنید؟ ایمیل‌های این پوشه برای همیشه حذف خواهند شد.",
    "Are you sure you want to delete this DKIM signature? This action cannot be undone.": "مطمئنید می‌خواهید این امضای DKIM را حذف کنید؟ این کار قابل بازگشت نیست.",
    "Are you sure you want to delete this group? This action cannot be undone.": "مطمئنید می‌خواهید این گروه را حذف کنید؟ این کار قابل بازگشت نیست.",
    "Are you sure you want to delete this mailing list? This action cannot be undone.": "مطمئنید می‌خواهید این فهرست پستی را حذف کنید؟ این کار قابل بازگشت نیست.",
    "Are you sure you want to delete this member? This action cannot be undone.": "مطمئنید می‌خواهید این عضو را حذف کنید؟ این کار قابل بازگشت نیست.",
    "Are you sure you want to delete this OAuth client? This action cannot be undone.": "مطمئنید می‌خواهید این سرویس‌گیرنده OAuth را حذف کنید؟ این کار قابل بازگشت نیست.",
    "Are you sure you want to delete this role? This action cannot be undone.": "مطمئنید می‌خواهید این نقش را حذف کنید؟ این کار قابل بازگشت نیست.",
    "Are you sure you want to disable this member? They will no longer be able to log in.": "مطمئنید می‌خواهید این عضو را غیرفعال کنید؟ دیگر نمی‌تواند وارد شود.",
    "Are you sure you want to empty the contents of this mailbox?": "مطمئنید می‌خواهید محتوای این صندوق پستی را خالی کنید؟",
    "Are you sure you want to enable this member? They will be able to log in again.": "مطمئنید می‌خواهید این عضو را فعال کنید؟ دوباره می‌تواند وارد شود.",
    "Are you sure you want to log out?": "مطمئنید می‌خواهید خارج شوید؟",
    "ARF": "ARF",
    "Ascending": "صعودی",
    "Ask whether to block the sender": "پیش از مسدود کردن فرستنده سؤال شود",
    "Assigned Email": "ایمیل اختصاص‌داده‌شده",
    "Attach files": "پیوست کردن فایل‌ها",
    "Audio Preview": "پیش‌نمایش صوتی",
    "Auto-generated if left blank": "اگر خالی بماند، خودکار ایجاد می‌شود",
    "Auto-reply to incoming mails while you’re away.": "هنگام نبودنتان، به ایمیل‌های دریافتی به‌طور خودکار پاسخ داده شود.",
    "Automatically creates contacts for new recipients after an email is sent.": "پس از ارسال ایمیل، برای گیرندگان جدید به‌طور خودکار مخاطب ایجاد می‌کند.",
    "Automatically deletes the email from your mailbox after it is sent.": "پس از ارسال، ایمیل را به‌طور خودکار از صندوق پستی شما حذف می‌کند.",
    "Automatically deletes the newsletter after it is sent.": "پس از ارسال، خبرنامه را به‌طور خودکار حذف می‌کند.",
    "Automatically mark emails as read when they are moved to this folder.": "ایمیل‌ها پس از انتقال به این پوشه، به‌طور خودکار خوانده‌شده علامت‌گذاری شوند.",
    "Automatically star emails when they are moved to this folder.": "ایمیل‌ها پس از انتقال به این پوشه، به‌طور خودکار ستاره‌دار شوند.",
    "awaiting acceptance": "در انتظار پذیرش",
    "awaiting delivery": "در انتظار تحویل",
    "Back to Mail": "بازگشت به ایمیل‌ها",
    "Backup Email": "ایمیل پشتیبان",
    "bcc": "bcc",
    "Bcc:": "Bcc:",
    "Cancel (delete) every message matching the current filter? This cannot be undone.": "همه پیام‌های مطابق با فیلتر فعلی لغو (حذف) شوند؟ این کار قابل بازگشت نیست.",
    "Cancel (delete) the selected messages? This cannot be undone.": "پیام‌های انتخاب‌شده لغو (حذف) شوند؟ این کار قابل بازگشت نیست.",
    "Cancel (delete) this queued message? This cannot be undone.": "این پیام در صف لغو (حذف) شود؟ این کار قابل بازگشت نیست.",
    "Cancel All": "لغو همه",
    "Cancel All Messages": "لغو همه پیام‌ها",
    "Cancel delivery": "لغو تحویل",
    "Cancel Delivery": "لغو تحویل",
    "Cancel Message": "لغو پیام",
    "Cancel Messages": "لغو پیام‌ها",
    "Cancel the scheduled delivery and move the message back to Drafts?": "تحویل زمان‌بندی‌شده لغو و پیام دوباره به پیش‌نویس‌ها منتقل شود؟",
    "Cancel the scheduled delivery?": "تحویل زمان‌بندی‌شده لغو شود؟",
    "Canonicalization": "متعارف‌سازی",
    "cc": "cc",
    "Cc and Bcc": "Cc و Bcc",
    "Check server logs": "گزارش‌های سرور را بررسی کنید",
    "Check to disable push notifications for this folder.": "برای غیرفعال کردن اعلان‌های فوری این پوشه، علامت بزنید.",
    "Clear all": "پاک کردن همه",
    "Clear All (Esc)": "پاک کردن همه (Esc)",
    "Clear All Mails": "پاک کردن همه ایمیل‌ها",
    "Clear filters": "پاک کردن فیلترها",
    "Client Secret": "راز سرویس‌گیرنده",
    "Comma-separated list of types to be notified for. Leave blank to be notified for all supported types.": "فهرست انواع اعلان‌ها با جداکننده ویرگول. برای دریافت اعلان همه انواع پشتیبانی‌شده، خالی بگذارید.",
    "Concluded deliveries — delivered, sent, or failed — will appear here.": "تحویل‌های پایان‌یافته — تحویل‌شده، ارسال‌شده یا ناموفق — اینجا نمایش داده می‌شوند.",
    "Connect a domain and set up its DNS records.": "دامنه‌ای را متصل و رکوردهای DNS آن را تنظیم کنید.",
    "Connection": "اتصال",
    "Contact removed.": "مخاطب حذف شد.",
    "Could not attach {0}.": "پیوست کردن {0} ممکن نشد.",
    "Could not delete signature": "حذف امضا ممکن نشد",
    "Could not start the delivery test.": "آغاز آزمایش تحویل ممکن نشد.",
    "Could not undo that.": "واگردانی انجام نشد.",
    "Could not update the Screener.": "غربال‌گر به‌روزرسانی نشد.",
    "Create a group to give a team a shared address and mailbox.": "گروهی بسازید تا یک نشانی و صندوق پستی مشترک به تیم اختصاص دهید.",
    "Create a mailing list to broadcast mail to many recipients at once.": "یک فهرست پستی بسازید تا ایمیل را هم‌زمان برای گیرندگان زیادی ارسال کنید.",
    "Create a new account": "ایجاد حساب جدید",
    "Credentials": "اطلاعات احراز هویت",
    "Credentials updated.": "اطلاعات احراز هویت به‌روزرسانی شد.",
    "CSV": "CSV",
    "date": "تاریخ",
    "Default Outgoing Email": "ایمیل خروجی پیش‌فرض",
    "Default Signature": "امضای پیش‌فرض",
    "Delete Address Book": "حذف دفترچه نشانی",
    "Delete Contact": "حذف مخاطب",
    "Delete Contacts": "حذف مخاطبان",
    "Delete DKIM Signature": "حذف امضای DKIM",
    "Delete Group": "حذف گروه",
    "Delete Mailing List": "حذف فهرست پستی",
    "Delete Member": "حذف عضو",
    "Delete OAuth Client": "حذف سرویس‌گیرنده OAuth",
    "Delete Report": "حذف گزارش",
    "Delete Reports": "حذف گزارش‌ها",
    "Delete Role": "حذف نقش",
    "Delete the selected reports? This cannot be undone.": "گزارش‌های انتخاب‌شده حذف شوند؟ این کار قابل بازگشت نیست.",
    "Delete this report? This cannot be undone.": "این گزارش حذف شود؟ این کار قابل بازگشت نیست.",
    "Delete {0} threads": "حذف {0} گفت‌وگو",
    "Deliver At": "زمان تحویل",
    "Deliver this email immediately instead of at the scheduled time?": "این ایمیل به‌جای زمان برنامه‌ریزی‌شده، همین حالا تحویل داده شود؟",
    "Delivered": "تحویل داده شد",
    "Delivered: {0}": "تحویل داده‌شده: {0}",
    "Deliveries you cancel will appear here.": "تحویل‌هایی که لغو می‌کنید اینجا نمایش داده می‌شوند.",
    "Delivery": "تحویل",
    "Delivery attempt scheduled.": "تلاش برای تحویل برنامه‌ریزی شد.",
    "Delivery cancelled.": "تحویل لغو شد.",
    "Delivery cancelled. The message is back in your drafts.": "تحویل لغو شد. پیام به پیش‌نویس‌های شما بازگشت.",
    "Delivery reports": "گزارش‌های تحویل",
    "Delivery rescheduled to {0}.": "تحویل برای {0} دوباره برنامه‌ریزی شد.",
    "Delivery status": "وضعیت تحویل",
    "Delivery status for {0}: {1}": "وضعیت تحویل برای {0}: {1}",
    "Delivery Test": "آزمایش تحویل",
    "Delivery to the recipient canceled.": "تحویل به گیرنده لغو شد.",
    "Delivery to {0} has been delayed. The server will keep trying until {1}.": "تحویل به {0} با تأخیر مواجه شده است. سرور تا {1} به تلاش ادامه می‌دهد.",
    "Delivery to {0} has been delayed. The server will keep trying.": "تحویل به {0} با تأخیر مواجه شده است. سرور به تلاش ادامه می‌دهد.",
    "Delivery Trace": "ردیابی تحویل",
    "Deny ({0})": "رد کردن ({0})",
    "Deny All": "رد کردن همه",
    "Deny all emails from {0}": "رد کردن همه ایمیل‌های ارسالی از {0}",
    "Deny All Senders": "رد کردن همه فرستندگان",
    "Deny Sender": "رد کردن فرستنده",
    "Directory": "فهرست کاربران",
    "Disable Member": "غیرفعال کردن عضو",
    "Disable Push Notifications": "غیرفعال کردن اعلان‌های فوری",
    "Disable Split View": "غیرفعال کردن نمای دو‌بخشی",
    "Disabled Permissions": "مجوزهای غیرفعال‌شده",
    "Disabling Push Notifications...": "در حال غیرفعال کردن اعلان‌های فوری...",
    "Discard ({0}+D)": "دور انداختن ({0}+D)",
    "Discard Draft": "دور انداختن پیش‌نویس",
    "Dismiss": "بستن",
    "Displayed: {0}": "نمایش‌داده‌شده: {0}",
    "DKIM signature deleted.": "امضای DKIM حذف شد.",
    "DKIM signature not found.": "امضای DKIM پیدا نشد.",
    "DKIM Signatures": "امضاهای DKIM",
    "DKIM signatures are generated automatically when you add a domain.": "هنگام افزودن دامنه، امضاهای DKIM به‌طور خودکار ایجاد می‌شوند.",
    "DMARC": "DMARC",
    "DNS changes may take up to 48 hours to propagate globally.": "انتشار جهانی تغییرات DNS ممکن است تا ۴۸ ساعت طول بکشد.",
    "DNS Records": "رکوردهای DNS",
    "Dock to corner": "چسباندن به گوشه",
    "Domain marked as trusted.": "دامنه به‌عنوان مورد اعتماد علامت‌گذاری شد.",
    "Domain not found.": "دامنه پیدا نشد.",
    "Don't load remote images from untrusted sources by default.": "تصاویر خارجی از منابع نامعتبر به‌طور پیش‌فرض بارگیری نشوند.",
    "Edit Draft": "ویرایش پیش‌نویس",
    "Edit General Information": "ویرایش اطلاعات عمومی",
    "Edit Group": "ویرایش گروه",
    "Edit here instead": "به‌جایش اینجا ویرایش کنید",
    "Edit Invite": "ویرایش دعوت‌نامه",
    "Edit Mailing List": "ویرایش فهرست پستی",
    "Edit Member": "ویرایش عضو",
    "Edit OAuth Client": "ویرایش سرویس‌گیرنده OAuth",
    "Edit Photo": "ویرایش عکس",
    "Edit Queued Message": "ویرایش پیام در صف",
    "Edit Quota": "ویرایش سهمیه",
    "Edit Recipient": "ویرایش گیرنده",
    "Edit Role": "ویرایش نقش",
    "Edit search": "ویرایش جست‌وجو",
    "Email Address": "نشانی ایمیل",
    "Email address added.": "نشانی ایمیل افزوده شد.",
    "Email address disabled.": "نشانی ایمیل غیرفعال شد.",
    "Email address enabled.": "نشانی ایمیل فعال شد.",
    "Email address removed.": "نشانی ایمیل حذف شد.",
    "Email Addresses": "نشانی‌های ایمیل",
    "Email addresses responsible for this application.": "نشانی‌های ایمیل افراد مسئول این برنامه.",
    "Email ID": "شناسه ایمیل",
    "Empty {0}": "خالی کردن {0}",
    "enable": "فعال کردن",
    "Enable Member": "فعال کردن عضو",
    "Enable Members": "فعال کردن اعضا",
    "Enable Push Notifications": "فعال کردن اعلان‌های فوری",
    "Enable Split View": "فعال کردن نمای دو‌بخشی",
    "enabled": "فعال",
    "Enabled Permissions": "مجوزهای فعال",
    "Enabling": "در حال فعال‌سازی",
    "Enabling Push Notifications...": "در حال فعال‌سازی اعلان‌های فوری...",
    "Enhanced Code": "کد وضعیت تکمیلی",
    "Enter the code sent to {0}.": "کد ارسال‌شده به {0} را وارد کنید.",
    "Envelope ID": "شناسه پاکت",
    "Envelope recipients": "گیرندگان پاکت",
    "Envelope sender": "فرستنده پاکت",
    "Error Type": "نوع خطا",
    "Event added to your calendar.": "رویداد به تقویم شما افزوده شد.",
    "Expand": "گسترش",
    "Expiration": "انقضا",
    "Explicitly denied, even if an inherited role grants them.": "صراحتاً رد شده‌اند، حتی اگر نقشی به‌ارث‌رسیده آن‌ها را اعطا کند.",
    "Export DNS": "خروجی گرفتن از DNS",
    "Failed to delete DKIM signature.": "حذف امضای DKIM ناموفق بود.",
    "Failed to delete member.": "حذف عضو ناموفق بود.",
    "Failed to load message source.": "بارگیری منبع پیام ناموفق بود.",
    "Failed to send reset password link.": "ارسال پیوند بازنشانی گذرواژه ناموفق بود.",
    "Failed to update action.": "به‌روزرسانی اقدام ناموفق بود.",
    "Failed to upload {0}": "بارگذاری {0} ناموفق بود",
    "File uploaded: {0}": "فایل بارگذاری شد: {0}",
    "Filter messages from this sender": "فیلتر کردن پیام‌های این فرستنده",
    "Filter Sender's Messages": "فیلتر کردن پیام‌های فرستنده",
    "Final": "نهایی",
    "First-time senders wait here until you decide.": "فرستندگان جدید تا زمانی که تصمیم بگیرید اینجا منتظر می‌مانند.",
    "Flags": "پرچم‌ها",
    "Folder Automation": "خودکارسازی پوشه",
    "Folder Automation Disabled": "خودکارسازی پوشه غیرفعال است",
    "Folder Automation enabled.": "خودکارسازی پوشه فعال شد.",
    "Folder automation rebuilt from your saved rules.": "خودکارسازی پوشه بر اساس قوانین ذخیره‌شده شما بازسازی شد.",
    "Folder created.": "پوشه ایجاد شد.",
    "Folder deleted.": "پوشه حذف شد.",
    "Folder Settings": "تنظیمات پوشه",
    "Folder updated.": "پوشه به‌روزرسانی شد.",
    "Folders": "پوشه‌ها",
    "Folders let you organize your emails into different categories.": "پوشه‌ها به شما امکان می‌دهند ایمیل‌هایتان را در دسته‌های مختلف سازمان‌دهی کنید.",
    "Follow what the mail server is doing.": "فعالیت سرور ایمیل را دنبال کنید.",
    "Forgot password?": "گذرواژه را فراموش کرده‌اید؟",
    "Forward (F)": "بازارسال (F)",
    "Forward Mail": "بازارسال ایمیل",
    "from": "از",
    "General Information": "اطلاعات عمومی",
    "Get the app on your device for easy access & a better experience!": "برای دسترسی آسان و تجربه‌ای بهتر، برنامه را روی دستگاه خود نصب کنید!",
    "Get the app on your iPhone for easy access & a better experience": "برای دسترسی آسان و تجربه‌ای بهتر، برنامه را روی iPhone خود نصب کنید",
    "Give someone a mailbox on your domains.": "در دامنه‌های خود به فردی صندوق پستی اختصاص دهید.",
    "Go to All Inboxes": "رفتن به همه صندوق‌های ورودی",
    "Go to Bottom of List": "رفتن به انتهای فهرست",
    "Go to Next Item": "رفتن به مورد بعدی",
    "Go to Previous Item": "رفتن به مورد قبلی",
    "Go to Screener": "رفتن به غربالگر",
    "Go to Starred": "رفتن به ستاره‌دارها",
    "Go to Top of List": "رفتن به ابتدای فهرست",
    "Granted to every account that holds this role.": "به همه حساب‌های دارای این نقش اعطا می‌شود.",
    "Group added.": "گروه افزوده شد.",
    "Group deleted.": "گروه حذف شد.",
    "Group Messages By": "گروه‌بندی پیام‌ها بر اساس",
    "Group not found.": "گروه یافت نشد.",
    "Group updated.": "گروه به‌روزرسانی شد.",
    "Groups": "گروه‌ها",
    "Hide trimmed content": "پنهان کردن محتوای کوتاه‌شده",
    "High": "بالا",
    "How the Screener works": "غربالگر چگونه کار می‌کند",
    "Identity created.": "هویت ایجاد شد.",
    "Import in progress. We'll email you when it's ready.": "درون‌ریزی در حال انجام است. پس از آماده‌شدن، به شما ایمیل می‌زنیم.",
    "in {0}": "در {0}",
    "Inbound": "ورودی",
    "Inbound Mail Routing": "مسیریابی ایمیل ورودی",
    "Inbound Reports": "گزارش‌های ورودی",
    "Inherited Roles": "نقش‌های به‌ارث‌رسیده",
    "Inspect and retry messages pending delivery.": "پیام‌های در انتظار تحویل را بررسی و دوباره ارسال کنید.",
    "Install": "نصب",
    "Install Frappe Mail": "نصب Frappe Mail",
    "Invitation email sent.": "ایمیل دعوت ارسال شد.",
    "Invitation Status": "وضعیت دعوت",
    "Invitations you send and self-signup requests will appear here until they are accepted.": "دعوت‌های ارسالی و درخواست‌های ثبت‌نام مستقیم تا زمان پذیرش در اینجا نمایش داده می‌شوند.",
    "Invite a member": "دعوت از عضو",
    "Invite people to give them a mailbox on your domains.": "از افراد دعوت کنید تا در دامنه‌های شما صندوق پستی داشته باشند.",
    "Invite updated.": "دعوت به‌روزرسانی شد.",
    "Invites deleted.": "دعوت‌ها حذف شدند.",
    "Items in this mailbox will be automatically deleted after 30 days.": "موارد این صندوق پستی پس از ۳۰ روز به‌طور خودکار حذف می‌شوند.",
    "john@example.com or @example.com": "john@example.com یا @example.com",
    "Joined On": "تاریخ پیوستن",
    "JSON": "JSON",
    "Keep Forwarded Email In Thread": "نگه‌داشتن ایمیل بازارسال‌شده در گفت‌وگو",
    "Keep forwarded emails in the same thread as the original by referencing it in the In-Reply-To header.": "با ارجاع به ایمیل اصلی در سرآیند In-Reply-To، ایمیل‌های بازارسال‌شده را در همان گفت‌وگو نگه دارید.",
    "Kind": "نوع",
    "Learn more.": "بیشتر بدانید.",
    "Leave blank to keep unchanged": "برای حفظ مقدار فعلی، خالی بگذارید",
    "Leave blank to use the configured default disk quota.": "برای استفاده از سهمیه پیش‌فرض پیکربندی‌شده دیسک، خالی بگذارید.",
    "Level": "سطح",
    "Light Mode": "حالت روشن",
    "Load Images": "بارگیری تصاویر",
    "Loading": "در حال بارگیری",
    "Locale": "زبان و منطقه",
    "Locality": "محل",
    "Log Entry": "مدخل گزارش",
    "Log entry not found.": "مدخل گزارش یافت نشد.",
    "Log In": "ورود",
    "Logo (URL or base64 encoded)": "نشان‌واره (URL یا کدگذاری‌شده با base64)",
    "Look In": "جست‌وجو در",
    "Look through every account you own — slower, but finds a mail wherever it landed.": "در همه حساب‌هایتان جست‌وجو کنید — کندتر است، اما ایمیل را هرجا باشد پیدا می‌کند.",
    "Low": "کم",
    "Mail Client Configuration": "پیکربندی نرم‌افزار ایمیل",
    "Mail deleted.": "ایمیل حذف شد.",
    "Mail Exchanges": "سرورهای تبادل ایمیل",
    "Mail marked as Junk.": "ایمیل به‌عنوان هرزنامه علامت‌گذاری شد.",
    "Mail marked as Not Junk.": "ایمیل به‌عنوان غیرهرزنامه علامت‌گذاری شد.",
    "Mail marked as {0}.": "ایمیل به‌عنوان {0} علامت‌گذاری شد.",
    "Mail moved back.": "ایمیل به محل قبلی بازگردانده شد.",
    "Mail moved to {0}.": "ایمیل به {0} منتقل شد.",
    "Mail moved.": "ایمیل منتقل شد.",
    "Mail routing records that ensure messages sent to your domain are delivered to the correct mail server.": "رکوردهای مسیریابی ایمیل که تضمین می‌کنند پیام‌های ارسالی به دامنه شما به سرور ایمیل درست تحویل داده شوند.",
    "Mail sent to this address is delivered to this group.": "ایمیل ارسالی به این نشانی به این گروه تحویل داده می‌شود.",
    "Mail sent to this address is delivered to this member's mailbox.": "ایمیل ارسالی به این نشانی به صندوق پستی این عضو تحویل داده می‌شود.",
    "Mail sent to this address is distributed to the list's recipients.": "ایمیل ارسالی به این نشانی میان گیرندگان فهرست پستی توزیع می‌شود.",
    "Mail server unavailable": "سرور ایمیل در دسترس نیست",
    "Mail {0}": "ایمیل {0}",
    "Mailbox": "صندوق پستی",
    "Mailing List": "فهرست پستی",
    "Mailing list added.": "فهرست پستی افزوده شد.",
    "Mailing list deleted.": "فهرست پستی حذف شد.",
    "Mailing list not found.": "فهرست پستی یافت نشد.",
    "Mailing list updated.": "فهرست پستی به‌روزرسانی شد.",
    "Mailing Lists": "فهرست‌های پستی",
    "Mails": "ایمیل‌ها",
    "Mails from sender will go to Junk.": "ایمیل‌های این فرستنده به هرزنامه می‌روند.",
    "Mark as Junk": "علامت‌گذاری به‌عنوان هرزنامه",
    "Mark as Junk (!)": "علامت‌گذاری به‌عنوان هرزنامه (!)",
    "Mark as Not Junk": "علامت‌گذاری به‌عنوان غیرهرزنامه",
    "Mark as Read (Shift+U)": "علامت‌گذاری به‌عنوان خوانده‌شده (Shift+U)",
    "Mark as Unread (U)": "علامت‌گذاری به‌عنوان خوانده‌نشده (U)",
    "Mark Domain as Trusted": "علامت‌گذاری دامنه به‌عنوان مورد اعتماد",
    "Mark Sender as Trusted": "علامت‌گذاری فرستنده به‌عنوان مورد اعتماد",
    "Mark Unread from Here": "علامت‌گذاری از اینجا به بعد به‌عنوان خوانده‌نشده",
    "Mark {0} threads as Read": "علامت‌گذاری {0} گفت‌وگو به‌عنوان خوانده‌شده",
    "Mark {0} threads as Unread": "علامت‌گذاری {0} گفت‌وگو به‌عنوان خوانده‌نشده",
    "Marking as Junk...": "در حال علامت‌گذاری به‌عنوان هرزنامه...",
    "Marking as Not Junk...": "در حال علامت‌گذاری به‌عنوان غیرهرزنامه...",
    "Match If": "تطبیق در صورت",
    "Max Attempts": "حداکثر تعداد تلاش‌ها",
    "Max Number of Contacts": "حداکثر تعداد مخاطبان",
    "Max Number of Emails": "حداکثر تعداد ایمیل‌ها",
    "Member added.": "عضو اضافه شد.",
    "Member deleted.": "عضو حذف شد.",
    "Member disabled.": "عضو غیرفعال شد.",
    "Member enabled.": "عضو فعال شد.",
    "Member invited.": "عضو دعوت شد.",
    "Member not found.": "عضو پیدا نشد.",
    "Member removed.": "عضو حذف شد.",
    "Member updated.": "عضو به‌روزرسانی شد.",
    "Members added.": "اعضا اضافه شدند.",
    "Members deleted.": "اعضا حذف شدند.",
    "Members disabled.": "اعضا غیرفعال شدند.",
    "Members enabled.": "اعضا فعال شدند.",
    "Membership Details": "جزئیات عضویت",
    "Message cancelled.": "پیام لغو شد.",
    "Message delivered": "پیام تحویل داده شد",
    "Message delivery delayed": "تحویل پیام به تأخیر افتاد",
    "Message Information": "اطلاعات پیام",
    "Message not delivered": "پیام تحویل داده نشد",
    "Message not found.": "پیام پیدا نشد.",
    "Message scheduled for retry.": "پیام برای تلاش مجدد زمان‌بندی شد.",
    "Message Source": "منبع پیام",
    "Messages cancelled.": "پیام‌ها لغو شدند.",
    "Messages from {0} senders will be moved to your Inbox. Future emails from them will still go to the Screener.": "پیام‌های {0} فرستنده به صندوق ورودی شما منتقل می‌شوند. ایمیل‌های بعدی آن‌ها همچنان به بخش غربالگری می‌روند.",
    "Messages scheduled for retry.": "پیام‌ها برای تلاش مجدد زمان‌بندی شدند.",
    "Messages waiting for delivery will appear here.": "پیام‌های منتظر تحویل اینجا نمایش داده می‌شوند.",
    "MIME Message": "پیام MIME",
    "Minimise": "کمینه کردن",
    "Monday morning": "صبح دوشنبه",
    "More actions": "اقدامات بیشتر",
    "Move All to Inbox": "انتقال همه به صندوق ورودی",
    "Move the sender's future emails to Junk automatically": "انتقال خودکار ایمیل‌های بعدی فرستنده به هرزنامه",
    "Move to Inbox": "انتقال به صندوق ورودی",
    "Move to Junk": "انتقال به هرزنامه",
    "Move to Trash (Delete)": "انتقال به زباله‌دان (حذف)",
    "Move unscreened messages?": "پیام‌های غربال‌نشده منتقل شوند؟",
    "Move {0} threads to Trash": "انتقال {0} گفت‌وگو به زباله‌دان",
    "Moving to Trash...": "در حال انتقال به زباله‌دان…",
    "Moving to {0}...": "در حال انتقال به {0}…",
    "New Address Book": "دفترچه نشانی جدید",
    "New Bcc": "Bcc جدید",
    "New Identity": "هویت جدید",
    "New member? Create an account.": "عضو جدید هستید؟ حسابی بسازید.",
    "New Push Subscription": "اشتراک جدید اعلان فوری",
    "New Reply To": "Reply-To جدید",
    "New senders wait here first": "فرستندگان جدید ابتدا اینجا منتظر می‌مانند",
    "New Sieve Script": "اسکریپت Sieve جدید",
    "New Signature": "امضای جدید",
    "Newest Emails": "جدیدترین ایمیل‌ها",
    "Next Notification": "اعلان بعدی",
    "Next Retry": "تلاش مجدد بعدی",
    "Next retry": "تلاش مجدد بعدی",
    "Next retry {0}": "تلاش مجدد بعدی {0}",
    "Next Thread (↓/J)": "گفت‌وگوی بعدی (↓/J)",
    "Next Transition": "انتقال بعدی",
    "No address books found.": "هیچ دفترچه نشانی‌ای پیدا نشد.",
    "No address books.": "هیچ دفترچه نشانی‌ای وجود ندارد.",
    "No addresses.": "هیچ نشانی‌ای وجود ندارد.",
    "No Archive folder for this account.": "این حساب پوشه بایگانی ندارد.",
    "No Bcc addresses added.": "هیچ نشانی Bcc اضافه نشده است.",
    "No calendar exchanges found.": "هیچ تبادل تقویمی پیدا نشد.",
    "No cancelled submissions": "هیچ ارسال لغوشده‌ای وجود ندارد",
    "No contacts exchanges found.": "هیچ تبادل مخاطبی پیدا نشد.",
    "No contacts found.": "هیچ مخاطبی پیدا نشد.",
    "No contacts to add.": "مخاطبی برای افزودن وجود ندارد.",
    "No contacts.": "هیچ مخاطبی وجود ندارد.",
    "No DKIM signatures yet": "هنوز هیچ امضای DKIM وجود ندارد",
    "No domains yet": "هنوز هیچ دامنه‌ای وجود ندارد",
    "No email addresses found.": "هیچ نشانی ایمیلی پیدا نشد.",
    "No emails.": "هیچ ایمیلی وجود ندارد.",
    "No exports in progress.": "هیچ خروجی‌گیری‌ای در حال انجام نیست.",
    "No final submissions": "هیچ ارسال نهایی‌ای وجود ندارد",
    "No folders found.": "هیچ پوشه‌ای پیدا نشد.",
    "No groups yet": "هنوز هیچ گروهی وجود ندارد",
    "No imports in progress.": "هیچ درون‌ریزی‌ای در حال انجام نیست.",
    "No log entries": "هیچ ورودی‌ای در گزارش وجود ندارد",
    "No mail exchanges found.": "هیچ سرور تبادل ایمیلی پیدا نشد.",
    "No mailing lists yet": "هنوز هیچ فهرست پستی‌ای وجود ندارد",
    "No mails found for the selected filter.": "هیچ ایمیلی برای فیلتر انتخاب‌شده پیدا نشد.",
    "No matching domains": "هیچ دامنه منطبقی وجود ندارد",
    "No matching groups": "هیچ گروه مطابقی یافت نشد",
    "No matching invites": "هیچ دعوت‌نامه مطابقی یافت نشد",
    "No matching log entries": "هیچ ورودی گزارش مطابقی یافت نشد",
    "No matching mailing lists": "هیچ فهرست پستی مطابقی یافت نشد",
    "No matching members": "هیچ عضو مطابقی یافت نشد",
    "No matching messages": "هیچ پیام مطابقی یافت نشد",
    "No matching OAuth clients": "هیچ سرویس‌گیرنده OAuth مطابقی یافت نشد",
    "No matching reports": "هیچ گزارش مطابقی یافت نشد",
    "No matching roles": "هیچ نقش مطابقی یافت نشد",
    "No matching submissions": "هیچ مورد ارسالی مطابقی یافت نشد",
    "No members found": "هیچ عضوی یافت نشد",
    "No members found.": "هیچ عضوی یافت نشد.",
    "No OAuth clients yet": "هنوز سرویس‌گیرنده OAuth وجود ندارد",
    "No pending invites": "هیچ دعوت‌نامه‌ای در انتظار نیست",
    "No pending submissions": "هیچ مورد ارسالی در انتظار نیست",
    "No phones.": "شماره تلفنی وجود ندارد.",
    "No push subscriptions.": "اشتراک اعلان فوری وجود ندارد.",
    "No recent log entries.": "ورودی گزارش اخیری وجود ندارد.",
    "No recipients found.": "هیچ گیرنده‌ای یافت نشد.",
    "No recipients.": "گیرنده‌ای وجود ندارد.",
    "No redirect URIs.": "هیچ URI تغییر مسیری وجود ندارد.",
    "No Reply To addresses added.": "هیچ نشانی «پاسخ به» افزوده نشده است.",
    "No reports yet": "هنوز گزارشی وجود ندارد",
    "No results found for the given query.": "نتیجه‌ای برای جستار داده‌شده یافت نشد.",
    "No roles yet": "هنوز نقشی وجود ندارد",
    "No screened senders match your search.": "هیچ فرستنده غربال‌شده‌ای با جست‌وجوی شما مطابقت ندارد.",
    "No screened senders.": "فرستنده غربال‌شده‌ای وجود ندارد.",
    "No sieve scripts found.": "هیچ اسکریپت Sieve یافت نشد.",
    "No signatures found.": "هیچ امضایی یافت نشد.",
    "No such folder for this account.": "چنین پوشه‌ای برای این حساب وجود ندارد.",
    "No Trash folder for this account.": "پوشه زباله‌دان برای این حساب وجود ندارد.",
    "Normal": "عادی",
    "Not a member of any group.": "عضو هیچ گروهی نیست.",
    "Not a recipient of any mailing list.": "گیرنده هیچ فهرست پستی‌ای نیست.",
    "Not configured": "پیکربندی نشده",
    "Not Junk": "هرزنامه نیست",
    "Not set": "تنظیم نشده",
    "Notify Count": "تعداد اعلان‌ها",
    "OAuth client added.": "سرویس‌گیرنده OAuth افزوده شد.",
    "OAuth client deleted.": "سرویس‌گیرنده OAuth حذف شد.",
    "OAuth client not found.": "سرویس‌گیرنده OAuth یافت نشد.",
    "OAuth client updated.": "سرویس‌گیرنده OAuth به‌روزرسانی شد.",
    "OAuth Clients": "سرویس‌گیرنده‌های OAuth",
    "OAuth clients let external apps authenticate with your mail server.": "سرویس‌گیرنده‌های OAuth به برنامه‌های خارجی امکان می‌دهند از طریق سرور ایمیل شما احراز هویت کنند.",
    "Oldest Emails": "قدیمی‌ترین ایمیل‌ها",
    "One email address per line": "در هر خط یک نشانی ایمیل",
    "Only the Administrator can run this action.": "فقط مدیر می‌تواند این عملیات را اجرا کند.",
    "Open Drafts": "باز کردن پیش‌نویس‌ها",
    "Open email": "باز کردن ایمیل",
    "Open Mail, or Fold Stack": "باز کردن ایمیل یا جمع کردن پشته",
    "Open Settings": "باز کردن تنظیمات",
    "Optional. Leave blank if the client authenticates without a secret.": "اختیاری است. اگر سرویس‌گیرنده بدون کلید محرمانه احراز هویت می‌کند، خالی بگذارید.",
    "Original Recipient": "گیرنده اولیه",
    "Outbound": "خروجی",
    "Outbound Reports": "گزارش‌های خروجی",
    "Outbox": "صندوق خروجی",
    "Overview": "نمای کلی",
    "Password resets and the invitation email are sent to this address.": "ایمیل‌های بازنشانی گذرواژه و دعوت‌نامه به این نشانی ارسال می‌شوند.",
    "Password updated.": "گذرواژه به‌روزرسانی شد.",
    "Permanent Failure": "شکست دائمی",
    "Permanently Delete": "حذف دائمی",
    "Phones": "شماره‌های تلفن",
    "Pick a date and time": "تاریخ و زمان را انتخاب کنید",
    "Please add at least one recipient.": "لطفاً حداقل یک گیرنده اضافه کنید.",
    "Please copy the API secret now. You won’t be able to see it again!": "لطفاً کلید محرمانه API را همین حالا کپی کنید. دیگر نمی‌توانید آن را ببینید!",
    "Please enable it to ensure that your rules function properly.": "لطفاً آن را فعال کنید تا قوانین شما به‌درستی کار کنند.",
    "Please pick a date and time.": "لطفاً تاریخ و زمان را انتخاب کنید.",
    "Please wait for attachments to finish uploading.": "لطفاً تا پایان بارگذاری پیوست‌ها صبر کنید.",
    "Policy Identifier": "شناسه خط‌مشی",
    "Pop Out": "باز کردن در پنجره جداگانه",
    "Postcode": "کد پستی",
    "Preview emails alongside the message list.": "پیش‌نمایش ایمیل‌ها را در کنار فهرست پیام‌ها نمایش دهید.",
    "Preview not available for this file type": "پیش‌نمایش برای این نوع فایل در دسترس نیست",
    "Previous Thread (↑/K)": "گفت‌وگوی قبلی (↑/K)",
    "Primary domain for company email": "دامنه اصلی ایمیل شرکت",
    "Primary Email": "ایمیل اصلی",
    "Privacy": "حریم خصوصی",
    "Profile photo updated.": "عکس نمایه به‌روزرسانی شد.",
    "Public Key": "کلید عمومی",
    "Push Notification permission denied": "مجوز اعلان فوری رد شد",
    "Push notifications disabled": "اعلان‌های فوری غیرفعال‌اند",
    "Push notifications have been disabled on your site": "اعلان‌های فوری در سایت شما غیرفعال شده‌اند",
    "Push subscription created.": "اشتراک اعلان فوری ایجاد شد.",
    "Push Subscriptions": "اشتراک‌های اعلان فوری",
    "Push subscriptions let your devices receive real-time notifications when your mail changes. Create one to register this or another client.": "اشتراک‌های اعلان فوری به دستگاه‌های شما امکان می‌دهند هنگام تغییر ایمیل‌ها، اعلان‌های لحظه‌ای دریافت کنند. برای ثبت این سرویس‌گیرنده یا سرویس‌گیرنده‌ای دیگر، یک اشتراک ایجاد کنید.",
    "Queue is empty": "صف خالی است",
    "Queued Message": "پیام در صف",
    "Queued message updated.": "پیام در صف به‌روزرسانی شد.",
    "Queued {0}": "{0} در صف قرار گرفت",
    "Quick Actions": "اقدام‌های سریع",
    "Quota (GB, 0 = unlimited)": "سهمیه (GB، 0 = نامحدود)",
    "Quota updated.": "سهمیه به‌روزرسانی شد.",
    "Quota Usage": "میزان استفاده از سهمیه",
    "Read receipts": "تأییدیه‌های خواندن",
    "Read Status": "وضعیت خواندن",
    "Rebuild Automation": "بازسازی خودکارسازی",
    "Received": "دریافت‌شده",
    "Received At": "زمان دریافت",
    "Received From IP": "دریافت‌شده از IP",
    "Received Via Port": "دریافت از طریق درگاه",
    "Recent Activity": "فعالیت اخیر",
    "Recipient": "گیرنده",
    "Recipient or domain": "گیرنده یا دامنه",
    "Recipient removed.": "گیرنده حذف شد.",
    "Recipient updated.": "گیرنده به‌روزرسانی شد.",
    "Recipients added.": "گیرندگان افزوده شدند.",
    "Recommended": "توصیه‌شده",
    "Records that allow mail and sync apps to automatically locate and connect to your domain’s email, calendar, and contacts services.": "رکوردهایی که به برنامه‌های ایمیل و همگام‌سازی امکان می‌دهند سرویس‌های ایمیل، تقویم و مخاطبان دامنه شما را به‌طور خودکار پیدا کنند و به آن‌ها متصل شوند.",
    "Recovery": "بازیابی",
    "Redirect URI removed.": "URI تغییر مسیر حذف شد.",
    "Redirect URIs": "URIهای تغییر مسیر",
    "Redirect URIs added.": "URIهای تغییر مسیر افزوده شدند.",
    "Redirecting...": "در حال تغییر مسیر...",
    "References": "ارجاع‌ها",
    "Regenerate Secret": "تولید مجدد کلید محرمانه",
    "Regenerate the folder automation script from your saved mailbox rules.": "اسکریپت خودکارسازی پوشه را از روی قوانین ذخیره‌شده صندوق پستی دوباره تولید کنید.",
    "Region": "منطقه",
    "Released at": "زمان آزادسازی",
    "Remember your password? Log in.": "گذرواژه‌تان را به خاطر دارید؟ وارد شوید.",
    "Remote content hidden to protect your privacy.": "برای حفظ حریم خصوصی شما، محتوای خارجی پنهان شده است.",
    "Remove Addresses": "حذف نشانی‌ها",
    "Remove Contacts": "حذف مخاطبان",
    "Remove Current Photo": "حذف عکس فعلی",
    "Remove Emails": "حذف ایمیل‌ها",
    "Remove filter": "حذف فیلتر",
    "Remove From": "حذف از",
    "Remove from Address Books": "حذف از دفترچه‌های نشانی",
    "Remove Phones": "حذف شماره‌های تلفن",
    "Remove Screened Senders": "حذف فرستندگان غربال‌شده",
    "Removed from group.": "از گروه حذف شد.",
    "Removed from mailing list.": "از فهرست پستی حذف شد.",
    "Renew": "تمدید",
    "Reply (R)": "پاسخ (R)",
    "Reply All (Shift+R)": "پاسخ به همه (Shift+R)",
    "Reply All to Mail": "پاسخ به همه در ایمیل",
    "Reply To": "پاسخ به",
    "reply to": "پاسخ به",
    "Reply to Mail": "پاسخ به ایمیل",
    "Report": "گزارش",
    "Report deleted.": "گزارش حذف شد.",
    "Report not found.": "گزارش پیدا نشد.",
    "Report Recipients": "گیرندگان گزارش",
    "Reports": "گزارش‌ها",
    "Reports deleted.": "گزارش‌ها حذف شدند.",
    "Reports received for your domains will appear here.": "گزارش‌های دریافتی برای دامنه‌های شما اینجا نمایش داده می‌شوند.",
    "Request failed.": "درخواست ناموفق بود.",
    "Request Reports": "درخواست گزارش‌ها",
    "Required": "الزامی",
    "Reschedule": "زمان‌بندی مجدد",
    "Reschedule delivery": "زمان‌بندی مجدد تحویل",
    "Resend code": "ارسال دوباره کد",
    "Reset password link sent to {0}.": "پیوند بازنشانی رمز عبور به {0} ارسال شد.",
    "Response Code": "کد پاسخ",
    "Response sent.": "پاسخ ارسال شد.",
    "Retries": "تلاش‌های مجدد",
    "Retries: {0}": "تلاش‌های مجدد: {0}",
    "Retry All": "تلاش مجدد برای همه",
    "Retry All Messages": "تلاش مجدد برای همه پیام‌ها",
    "Retry Count": "تعداد تلاش‌های مجدد",
    "Retry Messages": "تلاش مجدد برای پیام‌ها",
    "Retry Now": "اکنون دوباره تلاش کنید",
    "Retrying": "در حال تلاش مجدد",
    "Return to Home": "بازگشت به صفحه اصلی",
    "Review Now": "اکنون بررسی کنید",
    "Review the queue": "بررسی صف",
    "Role added.": "نقش افزوده شد.",
    "Role deleted.": "نقش حذف شد.",
    "Role not found.": "نقش یافت نشد.",
    "Role updated.": "نقش به‌روزرسانی شد.",
    "Roles control which permissions members have.": "نقش‌ها مجوزهای اعضا را تعیین می‌کنند.",
    "Rotation": "چرخش",
    "Run": "اجرا",
    "Run a delivery test": "اجرای آزمایش تحویل",
    "Run Another": "اجرای آزمایشی دیگر",
    "Run this action now?": "این عملیات اکنون اجرا شود؟",
    "Schedule every message matching the current filter for immediate delivery?": "همه پیام‌های مطابق با فیلتر فعلی برای تحویل فوری زمان‌بندی شوند؟",
    "Schedule send": "زمان‌بندی ارسال",
    "Schedule the selected messages for immediate delivery?": "پیام‌های انتخاب‌شده برای تحویل فوری زمان‌بندی شوند؟",
    "Scheduled": "زمان‌بندی‌شده",
    "Scheduled emails and deliveries still in flight will wait here.": "ایمیل‌های زمان‌بندی‌شده و موارد در حال تحویل، اینجا منتظر می‌مانند.",
    "Scheduled for": "زمان‌بندی‌شده برای",
    "Screen a Sender": "غربال فرستنده",
    "Screen New Senders": "غربال فرستندگان جدید",
    "Screen specific senders — or a whole domain (e.g. @example.com) — to either reject their messages or send them straight to Spam.": "فرستندگان مشخص — یا یک دامنه کامل (مثلاً @example.com) — را غربال کنید تا پیام‌هایشان رد شوند یا مستقیماً به هرزنامه فرستاده شوند.",
    "Screened Senders": "فرستندگان غربال‌شده",
    "Screener": "غربال‌گر",
    "Screener turned off.": "غربالگر خاموش شد.",
    "Screener turned on.": "غربالگر روشن شد.",
    "Screening is off. Move the messages currently in the Screener to your Inbox?": "غربالگری خاموش است. پیام‌های موجود در غربالگر به صندوق ورودی منتقل شوند؟",
    "Script Content": "محتوای اسکریپت",
    "Script Name": "نام اسکریپت",
    "Search ({0}+K)": "جست‌وجو ({0}+K)",
    "Search across all accounts": "جست‌وجو در همه حساب‌ها",
    "Search by email": "جست‌وجو بر اساس ایمیل",
    "Search by keyword": "جست‌وجو با کلیدواژه",
    "Search Mail": "جست‌وجو در ایمیل‌ها",
    "Search screened senders": "جست‌وجوی فرستندگان غربال‌شده",
    "Search your mail": "جست‌وجو در ایمیل‌ها",
    "Searching…": "در حال جست‌وجو…",
    "See MIME Message": "مشاهده پیام MIME",
    "Select a locale": "انتخاب تنظیمات منطقه‌ای",
    "Select a sender to view their emails.": "برای مشاهده ایمیل‌های فرستنده، او را انتخاب کنید.",
    "Select a time zone": "انتخاب منطقه زمانی",
    "Select All": "انتخاب همه",
    "Select All ({0}+A)": "انتخاب همه ({0}+A)",
    "Select All Mails": "انتخاب همه ایمیل‌ها",
    "Select an email to view the thread.": "برای مشاهده گفت‌وگو، یک ایمیل را انتخاب کنید.",
    "Select Contacts": "انتخاب مخاطبان",
    "Select From": "انتخاب فرستنده",
    "Select from contacts": "انتخاب از مخاطبان",
    "Selected subscriptions deleted.": "اشتراک‌های انتخاب‌شده حذف شدند.",
    "Selected subscriptions renewed.": "اشتراک‌های انتخاب‌شده تمدید شدند.",
    "Selector": "انتخابگر",
    "Send ({0}+Enter)": "ارسال ({0}+Enter)",
    "Send a password reset link to this member? The link will be emailed to their backup email address.": "پیوند بازنشانی گذرواژه برای این عضو ارسال شود؟ پیوند به نشانی ایمیل پشتیبان او فرستاده خواهد شد.",
    "Send Again": "ارسال دوباره",
    "Send again": "ارسال دوباره",
    "Send at": "زمان ارسال",
    "Send Invitation Email": "ارسال ایمیل دعوت",
    "Send Invite": "ارسال دعوت‌نامه",
    "Send Mail": "ارسال ایمیل",
    "Send Now": "ارسال اکنون",
    "Send now": "ارسال اکنون",
    "Send Reset Link": "ارسال پیوند بازنشانی",
    "Send scheduled.": "ارسال زمان‌بندی شد.",
    "Send this email again now?": "این ایمیل اکنون دوباره ارسال شود؟",
    "sender": "فرستنده",
    "Sender": "فرستنده",
    "Sender blocked.": "فرستنده مسدود شد.",
    "Sender marked as trusted.": "فرستنده به‌عنوان قابل اعتماد علامت‌گذاری شد.",
    "Sender screened.": "فرستنده غربال شد.",
    "Sender unblocked.": "انسداد فرستنده رفع شد.",
    "senders": "فرستندگان",
    "Senders blocked.": "فرستندگان مسدود شدند.",
    "Senders removed.": "فرستندگان حذف شدند.",
    "Senders unblocked.": "انسداد فرستندگان رفع شد.",
    "Sending": "در حال ارسال",
    "Sending undone. The message is back in your drafts.": "ارسال لغو شد. پیام به پیش‌نویس‌ها بازگشت.",
    "sends them to Junk.": "آن‌ها را به هرزنامه می‌فرستد.",
    "Server events will appear here as they happen.": "رویدادهای سرور هم‌زمان با وقوع در اینجا نمایش داده می‌شوند.",
    "Server Response": "پاسخ سرور",
    "Server URL": "URL سرور",
    "Service Configuration Records": "رکوردهای پیکربندی سرویس",
    "Service Discovery Records": "رکوردهای کشف سرویس",
    "Service records that enable automatic mail setup and enforce secure transport for your domain.": "رکوردهای سرویسی که راه‌اندازی خودکار ایمیل را فعال و انتقال امن را برای دامنه شما الزامی می‌کنند.",
    "Set Default": "تنظیم به‌عنوان پیش‌فرض",
    "Set Default Signature": "تنظیم امضای پیش‌فرض",
    "Set Up Your Domain": "راه‌اندازی دامنه",
    "Show quoted text": "نمایش متن نقل‌شده",
    "Show trimmed content": "نمایش محتوای پنهان‌شده",
    "Showing top 5 results. ": "نمایش ۵ نتیجه نخست. ",
    "Shown as the role's name across the dashboard.": "در سراسر پیشخوان به‌عنوان نام نقش نمایش داده می‌شود.",
    "Sieve script created.": "اسکریپت Sieve ایجاد شد.",
    "Sieve script deleted.": "اسکریپت Sieve حذف شد.",
    "Sieve script updated.": "اسکریپت Sieve به‌روزرسانی شد.",
    "Sieve scripts let you automatically filter and organize incoming emails.": "اسکریپت‌های Sieve به شما امکان می‌دهند ایمیل‌های ورودی را به‌طور خودکار فیلتر و مرتب کنید.",
    "Sign in to your account": "وارد حساب خود شوید",
    "Sign in using your existing mail account password.": "با گذرواژه فعلی حساب ایمیل خود وارد شوید.",
    "Sign-ins are only redirected back to one of these URLs.": "ورودها فقط به یکی از این URLها هدایت می‌شوند.",
    "Signature Body": "متن امضا",
    "Signature created.": "امضا ایجاد شد.",
    "Signature Name": "نام امضا",
    "Signature Type": "نوع امضا",
    "Signature updated.": "امضا به‌روزرسانی شد.",
    "Signatures": "امضاها",
    "Signatures let you automatically add personalized content to your emails.": "امضاها به شما امکان می‌دهند محتوای شخصی‌سازی‌شده را به‌طور خودکار به ایمیل‌هایتان اضافه کنید.",
    "Signed Headers": "سرآیندهای امضاشده",
    "SMTP Command": "فرمان SMTP",
    "Sort By": "مرتب‌سازی بر اساس",
    "Split View": "نمای دو‌بخشی",
    "Stage": "مرحله",
    "Star": "ستاره",
    "Star Mail": "ستاره‌دار کردن ایمیل",
    "Starred Mails": "ایمیل‌های ستاره‌دار",
    "Start From": "شروع از",
    "Start Test": "شروع آزمایش",
    "Stop": "توقف",
    "Street": "خیابان",
    "subject": "موضوع",
    "Subject Contains": "موضوع شامل",
    "Submission ID": "شناسه ارسال",
    "Submission not found.": "ارسال یافت نشد.",
    "Subscription ID": "شناسه اشتراک",
    "Supported file format: .eml": "قالب فایل پشتیبانی‌شده: .eml",
    "Supported file format: .vcf": "قالب فایل پشتیبانی‌شده: .vcf",
    "Supported file formats: .zip, .tar, .tgz": "قالب‌های فایل پشتیبانی‌شده: .zip، .tar، .tgz",
    "System Default": "پیش‌فرض سیستم",
    "Takes input": "ورودی می‌پذیرد",
    "Tap": "لمس کنید",
    "Temporary Failure": "خطای موقت",
    "Test SMTP Delivery": "آزمایش تحویل SMTP",
    "Testing delivery…": "در حال آزمایش تحویل…",
    "The client can no longer be used after this time.": "پس از این زمان، دیگر نمی‌توان از سرویس‌گیرنده استفاده کرد.",
    "The delivery failed. Try to send this email again now?": "تحویل ناموفق بود. این ایمیل اکنون دوباره ارسال شود؟",
    "The delivery time cannot be more than {0} days ahead.": "زمان تحویل نمی‌تواند بیش از {0} روز بعد باشد.",
    "The delivery time must be in the future.": "زمان تحویل باید در آینده باشد.",
    "The first time someone emails you, their message lands in the Screener instead of your Inbox.": "وقتی کسی برای نخستین‌بار به شما ایمیل می‌زند، پیام او به‌جای صندوق ورودی وارد غربال‌گر می‌شود.",
    "The invitation link stops working after this time.": "پیوند دعوت پس از این زمان دیگر کار نمی‌کند.",
    "The mail server is temporarily unavailable. Please try again in a few minutes.": "سرور ایمیل موقتاً در دسترس نیست. لطفاً چند دقیقه دیگر دوباره تلاش کنید.",
    "The mail server this account connects to. Set by your administrator.": "سرور ایمیلی که این حساب به آن متصل می‌شود. مدیر آن را تنظیم کرده است.",
    "The member can change this later in their account settings.": "عضو می‌تواند بعداً این مورد را در تنظیمات حساب خود تغییر دهد.",
    "The next delivery attempt is scheduled for this time.": "تلاش بعدی برای تحویل در این زمان برنامه‌ریزی شده است.",
    "The original message was deleted after scheduling, so only the envelope details remain.": "پیام اصلی پس از زمان‌بندی حذف شد؛ بنابراین فقط جزئیات پاکت باقی مانده است.",
    "The request can no longer create an account after this time.": "پس از این زمان، دیگر نمی‌توان با این درخواست حسابی ایجاد کرد.",
    "The response from the remote server was:": "پاسخ سرور راه‌دور:",
    "The unique identifier the application uses to identify itself.": "شناسه منحصربه‌فردی که برنامه برای شناسایی خود استفاده می‌کند.",
    "then": "سپس",
    "These fields are required: {0}": "این فیلدها الزامی‌اند: {0}",
    "This draft is open in another window.": "این پیش‌نویس در پنجره دیگری باز است.",
    "This is the primary address and cannot be removed.": "این نشانی اصلی است و نمی‌توان آن را حذف کرد.",
    "This role also grants everything the selected roles allow.": "این نقش تمام مجوزهای نقش‌های انتخاب‌شده را نیز اعطا می‌کند.",
    "This sender is already screened.": "این فرستنده قبلاً غربال شده است.",
    "This sender is blocked": "این فرستنده مسدود است",
    "Thread": "گفت‌وگو",
    "thread": "گفت‌وگو",
    "Thread added back.": "گفت‌وگو بازگردانده شد.",
    "Thread added to folder.": "گفت‌وگو به پوشه اضافه شد.",
    "Thread added to {0}.": "گفت‌وگو به {0} اضافه شد.",
    "Thread archived.": "گفت‌وگو بایگانی شد.",
    "Thread deleted.": "گفت‌وگو حذف شد.",
    "Thread ID": "شناسه گفت‌وگو",
    "Thread is no longer in the list.": "گفت‌وگو دیگر در فهرست نیست.",
    "Thread marked as {0}.": "گفت‌وگو به‌عنوان {0} علامت‌گذاری شد.",
    "Thread moved back.": "گفت‌وگو بازگردانده شد.",
    "Thread moved to Trash.": "گفت‌وگو به زباله‌دان منتقل شد.",
    "Thread moved to {0}.": "گفت‌وگو به {0} منتقل شد.",
    "Thread moved.": "گفت‌وگو منتقل شد.",
    "Thread removed from folder.": "گفت‌وگو از پوشه حذف شد.",
    "Thread removed from {0}.": "گفت‌وگو از {0} حذف شد.",
    "threads": "گفت‌وگوها",
    "Threads": "گفت‌وگوها",
    "Threads added back.": "گفت‌وگوها بازگردانده شدند.",
    "Threads added to {0}.": "گفت‌وگوها به {0} اضافه شدند.",
    "Threads archived.": "گفت‌وگوها بایگانی شدند.",
    "Threads deleted.": "گفت‌وگوها حذف شدند.",
    "Threads marked as {0}.": "گفت‌وگوها به‌عنوان {0} علامت‌گذاری شدند.",
    "Threads moved back.": "گفت‌وگوها بازگردانده شدند.",
    "Threads moved to Trash.": "گفت‌وگوها به زباله‌دان منتقل شدند.",
    "Threads moved to {0}.": "گفت‌وگوها به {0} منتقل شدند.",
    "Threads removed from {0}.": "گفت‌وگوها از {0} حذف شدند.",
    "Timestamp": "مُهر زمانی",
    "TLS": "TLS",
    "To add a domain, you must already own it. If you don't have one, purchase one and return here.": "برای افزودن دامنه، باید مالک آن باشید. اگر دامنه‌ای ندارید، یکی بخرید و به اینجا بازگردید.",
    "to {0}": "به {0}",
    "to {0} and {1}": "به {0} و {1}",
    "to {0}, {1} and {2}": "به {0}، {1} و {2}",
    "to {0}, {1} and {2} others": "به {0}، {1} و {2} نفر دیگر",
    "To:": "به:",
    "Together with the domain, this forms the group's email address.": "این عبارت همراه با دامنه، نشانی ایمیل گروه را تشکیل می‌دهد.",
    "Together with the domain, this forms the list's email address.": "این عبارت همراه با دامنه، نشانی ایمیل فهرست را تشکیل می‌دهد.",
    "Toggle Select Downwards": "تغییر وضعیت انتخاب به سمت پایین",
    "Toggle Select Upwards": "تغییر وضعیت انتخاب به سمت بالا",
    "Tomorrow afternoon": "فردا بعدازظهر",
    "Tomorrow morning": "فردا صبح",
    "Total Contacts": "مجموع مخاطبان",
    "Total Quota": "سهمیه کل",
    "Trace a live SMTP delivery to any recipient or domain to diagnose DNS, connection and handshake issues.": "تحویل زنده SMTP به هر گیرنده یا دامنه را برای عیب‌یابی مشکلات DNS، اتصال و دست‌دهی ردیابی کنید.",
    "Trace a live SMTP delivery to diagnose issues.": "برای عیب‌یابی مشکلات، تحویل زنده SMTP را ردیابی کنید.",
    "Track status": "پیگیری وضعیت",
    "Try adjusting the filters.": "فیلترها را تنظیم کنید.",
    "Try adjusting your search or filters.": "جستجو یا فیلترها را تنظیم کنید.",
    "Try again now": "اکنون دوباره امتحان کنید",
    "TTL (Recommended)": "TTL (پیشنهادی)",
    "TXT records that enforce encrypted mail delivery and provide reporting on failed or insecure SMTP connections.": "رکوردهای TXT که تحویل رمزگذاری‌شده ایمیل را الزامی می‌کنند و درباره اتصال‌های ناموفق یا ناامن SMTP گزارش می‌دهند.",
    "Type something...": "چیزی بنویسید...",
    "Types": "انواع",
    "Unable to save appearance settings.": "ذخیره تنظیمات ظاهر ممکن نیست.",
    "Unable to save credentials.": "ذخیره اطلاعات ورود ممکن نیست.",
    "Unable to update Split View.": "به‌روزرسانی نمای دو‌بخشی ممکن نیست.",
    "Unblock": "رفع مسدودی",
    "Unblock Sender": "رفع مسدودی فرستنده",
    "Undo Last Action": "واگرد آخرین اقدام",
    "Undoing...": "در حال واگرد...",
    "Uniquely identifies the client and device.": "سرویس‌گیرنده و دستگاه را به‌طور یکتا شناسایی می‌کند.",
    "Unknown": "ناشناخته",
    "Unlimited": "نامحدود",
    "Unlimited ({0} used)": "نامحدود ({0} استفاده‌شده)",
    "unread": "خوانده‌نشده",
    "Unread Mails": "ایمیل‌های خوانده‌نشده",
    "Unscreened messages moved to Inbox.": "پیام‌های بررسی‌نشده به صندوق ورودی منتقل شدند.",
    "Unselect All": "لغو انتخاب همه",
    "Unstar": "برداشتن ستاره",
    "Unstar Mail": "برداشتن ستاره ایمیل",
    "Untitled event": "رویداد بدون عنوان",
    "Updated On": "تاریخ به‌روزرسانی",
    "Upload New Photo": "بارگذاری عکس جدید",
    "Uploading ({0}%)": "در حال بارگذاری ({0}٪)",
    "Use Saved Signature": "استفاده از امضای ذخیره‌شده",
    "Use these details to connect a third-party mail client such as Thunderbird or the Gmail app.": "برای اتصال سرویس‌گیرنده ایمیل شخص ثالث مانند Thunderbird یا برنامه Gmail از این اطلاعات استفاده کنید.",
    "Used as the display name for this address": "به‌عنوان نام نمایشی این نشانی استفاده می‌شود",
    "Used to connect to your mailbox.": "برای اتصال به صندوق پستی شما استفاده می‌شود.",
    "user@example.com": "user@example.com",
    "Vacation Response": "پاسخ خودکار در تعطیلات",
    "Vacation response updated.": "پاسخ خودکار در تعطیلات به‌روزرسانی شد.",
    "Verification Code": "کد تأیید",
    "Verify": "تأیید",
    "Video Preview": "پیش‌نمایش ویدئو",
    "View history": "مشاهده تاریخچه",
    "View in Calendar": "مشاهده در تقویم",
    "View in Desk": "مشاهده در میزکار",
    "View Logs": "مشاهده گزارش‌ها",
    "View more.": "مشاهده بیشتر",
    "View remaining attachments": "مشاهده پیوست‌های باقی‌مانده",
    "View Shortcuts": "مشاهده میان‌برها",
    "View Source": "مشاهده منبع",
    "We have sent an email to {0}. Please click on the link received to reset your password.": "ایمیلی به {0} ارسال کردیم. برای بازنشانی گذرواژه، روی پیوند دریافتی کلیک کنید.",
    "We'll contact you here if there's an issue with your main account.": "اگر مشکلی برای حساب اصلی شما پیش بیاید، از این طریق با شما تماس می‌گیریم.",
    "When Marking as Junk": "هنگام علامت‌گذاری به‌عنوان هرزنامه",
    "Where the JMAP server sends push messages. Leave blank to use this app's default endpoint. Must start with https://.": "نشانی‌ای که سرور JMAP پیام‌های push را به آن می‌فرستد. برای استفاده از نقطه پایانی پیش‌فرض این برنامه، خالی بگذارید. باید با https:// شروع شود.",
    "With Attachments": "دارای پیوست",
    "With attachments": "دارای پیوست",
    "Without Attachments": "بدون پیوست",
    "Work": "کاری",
    "Work Contacts": "مخاطبان کاری",
    "Work signature": "امضای کاری",
    "Write your signature here": "امضای خود را اینجا بنویسید",
    "Yes, {0} {1}": "بله، {0} {1}",
    "You can undo decisions or turn the Screener off in": "می‌توانید تصمیم‌ها را واگرد کنید یا غربال‌گر را در این بخش خاموش کنید:",
    "You don't have an API key yet. Generate one to access the API.": "هنوز کلید API ندارید. برای دسترسی به API یک کلید ایجاد کنید.",
    "You have been signed out. Please sign in again.": "از حساب خارج شده‌اید. لطفاً دوباره وارد شوید.",
    "You have no mails in any inbox.": "در هیچ صندوق ورودی‌ای ایمیلی ندارید.",
    "You have no mails in this folder.": "در این پوشه ایمیلی ندارید.",
    "You have no new senders to screen.": "فرستنده جدیدی برای بررسی ندارید.",
    "You won't receive future messages from the selected senders.": "دیگر از فرستندگان انتخاب‌شده پیامی دریافت نخواهید کرد.",
    "You won't receive future messages from {0}.": "دیگر از {0} پیامی دریافت نخواهید کرد.",
    "Your message couldn't be delivered to {0}.": "پیام شما به {0} تحویل داده نشد.",
    "Your message was delivered to {0}.": "پیام شما به {0} تحویل داده شد.",
    "Zone File": "فایل Zone",
    "{0} + {1} more": "{0} + {1} مورد دیگر",
    "{0} allowed.": "{0} مجاز شد.",
    "{0} are back in the Screener.": "{0} دوباره به غربالگر برگشتند.",
    "{0} are waiting to be screened.": "{0} در انتظار بررسی هستند.",
    "{0} attachments": "{0} پیوست",
    "{0} conversations": "{0} گفت‌وگو",
    "{0} deactivated.": "{0} غیرفعال شد.",
    "{0} denied.": "{0} مسدود شد.",
    "{0} disabled": "{0} غیرفعال",
    "{0} emptied.": "{0} خالی شد.",
    "{0} Enabled": "{0} فعال",
    "{0} is back in the Screener.": "{0} دوباره به غربالگر برگشت.",
    "{0} is currently on your": "{0} اکنون در فهرست شماست:",
    "{0} is required.": "{0} الزامی است.",
    "{0} is waiting to be screened.": "{0} در انتظار بررسی است.",
    "{0} Mail archived.": "{0} ایمیل بایگانی شد.",
    "{0} Mail moved to Trash.": "{0} ایمیل به زباله‌دان منتقل شد.",
    "{0} marked as unread.": "{0} به‌عنوان خوانده‌نشده علامت‌گذاری شد.",
    "{0} members": "{0} عضو",
    "{0} messages": "{0} پیام",
    "{0} more messages": "{0} پیام دیگر",
    "{0} new messages": "{0} پیام جدید",
    "{0} new senders": "{0} فرستنده جدید",
    "{0} new threads": "{0} گفت‌وگوی جدید",
    "{0} of {1} selected": "{0} از {1} انتخاب شده",
    "{0} of {1} used": "{0} از {1} استفاده شده",
    "{0} recipients": "{0} گیرنده",
    "{0} redirect URIs": "{0} URI تغییر مسیر",
    "{0} remote images hidden to protect your privacy.": "برای حفظ حریم خصوصی شما، {0} تصویر راه‌دور پنهان شد.",
    "{0} results": "{0} نتیجه",
    "{0} selected": "{0} انتخاب شده",
    "{0} senders": "{0} فرستنده",
    "{0} senders will be allowed, and their messages moved to your Inbox.": "{0} فرستنده مجاز خواهند شد و پیام‌هایشان به صندوق ورودی شما منتقل می‌شود.",
    "{0} senders will be denied, and their messages moved to Junk.": "{0} فرستنده مسدود خواهند شد و پیام‌هایشان به هرزنامه منتقل می‌شود.",
    "{0} threads": "{0} گفت‌وگو",
    "{0} used · Unlimited": "{0} استفاده شده · نامحدود",
    "{0} {1} will {2} {3}. Do you want to proceed?": "{0} {1}، {2} {3} خواهد شد. می‌خواهید ادامه دهید؟",
    "{0} {1}.": "{0} {1}.",
    "{0} {1}?": "{0} {1}؟",
    "{0}% of {1} used": "{0}٪ از {1} استفاده شده",
    "{0}–{1} of {2}": "{0}–{1} از {2}",
    "— No message body —": "— بدون متن پیام —",
    "---------- Forwarded message ---------": "---------- پیام بازارسال‌شده ---------",
    "Authenticated As": "هویت احرازشده",
    "Doe": "رضایی",
    "EHLO Domain": "دامنه EHLO",
    "Email, Mailbox": "ایمیل، صندوق پستی",
    "Frappe Mail": "ایمیل فراپه",
    "Important, Urgent, Follow Up": "مهم، فوری، پیگیری",
    "John": "علی",
    "MAIL FROM": "MAIL FROM",
    "MAIL FROM Parameters": "پارامترهای MAIL FROM",
    "Message Body": "متن پیام",
    "On {0}, {1} wrote:": "در {0}، {1} نوشت:",
    "Out of Office": "خارج از دفتر",
    "Random": "تصادفی",
    "RCPT TO": "RCPT TO",
    "Remote IP": "IP راه دور",
    "SPF EHLO Domain": "دامنه EHLO برای SPF",
    "SPF MAIL FROM Domain": "دامنه MAIL FROM برای SPF",
    "TLS Enabled": "TLS فعال",
}
