"""Reviewed Persian terminology for Suite's high-frequency user interface."""

PERSIAN_OVERRIDES = {
    "Frappe Suite": "مجموعه فرپ",
    "Frappe Sheets": "صفحه‌گسترده فرپ",
    "Drive": "فضای فایل",
    "Slides": "ارائه‌ها",
    "Writer": "سندها",
    "Sheets": "صفحه‌گسترده",
    "Meet": "جلسه",
    "Mail": "ایمیل",
    "Calendar": "تقویم",
    "Desk": "میزکار",
    "Settings": "تنظیمات",
    "Settings logo": "نشان تنظیمات",
    "{0} logo": "نشان {0}",
    "Page not found": "صفحه پیدا نشد",
    "Back to launcher": "بازگشت به فهرست برنامه‌ها",
    "Apps": "برنامه‌ها",
    "Accounts": "حساب‌ها",
    "Log Out": "خروج",
    "Search": "جستجو",
    "Search sheets…": "جستجوی صفحه‌گسترده‌ها…",
    "Actions": "عملیات",
    "Explore": "مشاهده",
    "Add": "افزودن",
    "Edit": "ویرایش",
    "Delete": "حذف",
    "Remove": "حذف",
    "Rename": "تغییر نام",
    "Duplicate": "ساخت نسخه کپی",
    "Copy": "کپی",
    "Copy Link": "کپی پیوند",
    "Download": "دریافت",
    "Upload": "بارگذاری",
    "Move": "انتقال",
    "Share": "اشتراک‌گذاری",
    "Save": "ذخیره",
    "Cancel": "انصراف",
    "Close": "بستن",
    "Confirm": "تأیید",
    "Done": "تمام",
    "New": "جدید",
    "Create": "ایجاد",
    "Open": "باز کردن",
    "View": "نمایش",
    "Preview": "پیش‌نمایش",
    "Print": "چاپ",
    "Export": "خروجی گرفتن",
    "Import": "ورود اطلاعات",
    "Refresh": "تازه‌سازی",
    "Retry": "تلاش دوباره",
    "Try Again": "تلاش دوباره",
    "Continue": "ادامه",
    "Next": "بعدی",
    "Previous": "قبلی",
    "Back": "بازگشت",
    "Home": "خانه",
    "Back to Home": "بازگشت به خانه",
    "Sign In": "ورود",
    "Sign Out": "خروج",
    "Login": "ورود",
    "Name": "نام",
    "Title": "عنوان",
    "Date": "تاریخ",
    "Start": "شروع",
    "End": "پایان",
    "Owner": "مالک",
    "Last Modified": "آخرین تغییر",
    "Description": "توضیحات",
    "Status": "وضعیت",
    "Type": "نوع",
    "Folder": "پوشه",
    "File": "فایل",
    "Files": "فایل‌ها",
    "People": "افراد",
    "Participants": "شرکت‌کنندگان",
    "Guest": "مهمان",
    "Host": "میزبان",
    "Organizer": "برگزارکننده",
    "Public": "عمومی",
    "Private": "خصوصی",
    "Today": "امروز",
    "Yesterday": "دیروز",
    "Week": "هفته",
    "Month": "ماه",
    "Day": "روز",
    "Minutes": "دقیقه",
    "Hours": "ساعت",
    "Days": "روز",
    "Weeks": "هفته",
    "Yes": "بله",
    "No": "خیر",
    "Maybe": "شاید",
    "Loading...": "در حال بارگذاری…",
    "Loading…": "در حال بارگذاری…",
    "No results": "نتیجه‌ای پیدا نشد",
    "No rows.": "ردیفی وجود ندارد.",
    "No data": "داده‌ای وجود ندارد",
    "Untitled": "بدون عنوان",
    "Untitled Sheet": "صفحه‌گسترده بدون عنوان",
    "New Sheet": "صفحه‌گسترده جدید",
    "No sheets yet": "هنوز صفحه‌گسترده‌ای ندارید",
    "Create one to get started": "برای شروع یک صفحه‌گسترده بسازید",
    "Create one to get started.": "برای شروع یک صفحه‌گسترده بسازید.",
    "Try a different name.": "نام دیگری را جستجو کنید.",
    "No matches for “{0}”": "موردی برای «{0}» پیدا نشد",
    "Shared": "اشتراکی",
    "List view": "نمایش فهرستی",
    "Grid view": "نمایش شبکه‌ای",
    "View mode": "نوع نمایش",
    "Rename sheet": "تغییر نام صفحه‌گسترده",
    "New title": "عنوان جدید",
    "Delete sheet?": "صفحه‌گسترده حذف شود؟",
    "“{0}” will be permanently deleted.": "«{0}» برای همیشه حذف می‌شود.",
    "Delete failed": "حذف انجام نشد",
    "Duplicate failed": "ساخت نسخه کپی انجام نشد",
    "just now": "همین حالا",
    "{0}m ago": "{0} دقیقه پیش",
    "{0}h ago": "{0} ساعت پیش",
    "{0}d ago": "{0} روز پیش",
    "Presentations": "ارائه‌ها",
    "Presentation": "ارائه",
    "No presentations created yet.": "هنوز ارائه‌ای ساخته نشده است.",
    "Slideshow": "نمایش اسلایدها",
    "Slide": "اسلاید",
    "New Presentation": "ارائه جدید",
    "Start Presentation": "شروع ارائه",
    "Access Denied": "دسترسی مجاز نیست",
    "You do not have permission to access this page.": "شما اجازه دسترسی به این صفحه را ندارید.",
    "Documents": "سندها",
    "No documents found": "سندی پیدا نشد",
    "Table of Contents": "فهرست مطالب",
    "Versions": "نسخه‌ها",
    "Templates": "الگوها",
    "Clear Cache": "پاک‌کردن حافظه موقت",
    "Lock": "قفل",
    "Wide": "عریض",
    "Markdown": "مارک‌داون",
    "Blog": "وبلاگ",
    "You're offline": "اتصال شما قطع است",
    "Try out Drive": "امتحان فضای فایل",
    "Hey {0},": "سلام {0}،",
    "there": "دوست عزیز",
    "Start an open meeting, create a restricted meeting, or join with a code.": "یک جلسه عمومی یا محدود بسازید، یا با کد وارد جلسه شوید.",
    "Instant meet": "جلسه فوری",
    "Restricted meet": "جلسه محدود",
    "Schedule meet": "زمان‌بندی جلسه",
    "Join with code": "ورود با کد",
    "Join with meeting code": "ورود با کد جلسه",
    "Join": "ورود به جلسه",
    "Schedule": "زمان‌بندی",
    "Team meeting": "جلسه تیمی",
    "Creating meeting...": "در حال ساخت جلسه…",
    "Creating restricted meeting...": "در حال ساخت جلسه محدود…",
    "Meeting created successfully!": "جلسه با موفقیت ساخته شد.",
    "Restricted meeting created successfully!": "جلسه محدود با موفقیت ساخته شد.",
    "Failed to create meeting. Please try again.": "ساخت جلسه انجام نشد. دوباره تلاش کنید.",
    "Meeting scheduled.": "جلسه زمان‌بندی شد.",
    "Scheduling meeting...": "در حال زمان‌بندی جلسه…",
    "Failed to schedule meeting. Please try again.": "زمان‌بندی جلسه انجام نشد. دوباره تلاش کنید.",
    "Set up Calendar before scheduling a Meet.": "پیش از زمان‌بندی جلسه، تقویم را راه‌اندازی کنید.",
    "Could not load Calendar account.": "حساب تقویم بارگذاری نشد.",
    "Enter a valid date and an end time after the start time.": "تاریخ معتبر و زمانی برای پایان که پس از زمان شروع باشد وارد کنید.",
    "Please enter a meeting code": "کد جلسه را وارد کنید",
    "Please enter a valid meeting code (format: xxxx-xxxx-xxxx)": "کد معتبر جلسه را با قالب xxxx-xxxx-xxxx وارد کنید",
    "Ready to join?": "آماده ورود هستید؟",
    "Join Meeting": "ورود به جلسه",
    "Leave": "خروج از جلسه",
    "Chat": "گفتگو",
    "No messages yet": "هنوز پیامی نیست",
    "Waiting to join": "در انتظار ورود",
    "Waiting to be admitted": "در انتظار تأیید ورود",
    "The meeting host will let you in soon.": "میزبان به‌زودی ورود شما را تأیید می‌کند.",
    "Admit": "اجازه ورود",
    "Admit all": "اجازه ورود به همه",
    "Deny": "رد کردن",
    "Remove from meeting": "حذف از جلسه",
    "Meeting ID": "شناسه جلسه",
    "Meeting URL": "پیوند جلسه",
    "Upcoming meetings": "جلسه‌های پیشِ رو",
    "No upcoming Meet meetings": "جلسه‌ای در پیش نیست",
    "Create Poll": "ساخت نظرسنجی",
    "Add Option": "افزودن گزینه",
    "Poll": "نظرسنجی",
    "Options": "گزینه‌ها",
    "Inbox": "صندوق ورودی",
    "All Inboxes": "همه صندوق‌های ورودی",
    "Compose": "نوشتن ایمیل",
    "Send": "ارسال",
    "Discard": "کنار گذاشتن",
    "Draft": "پیش‌نویس",
    "Drafts": "پیش‌نویس‌ها",
    "Sent": "ارسال‌شده",
    "Starred": "ستاره‌دار",
    "Trash": "زباله‌دان",
    "Junk": "هرزنامه",
    "Subject": "موضوع",
    "From": "از",
    "To": "به",
    "Cc": "رونوشت",
    "Bcc": "رونوشت پنهان",
    "Reply": "پاسخ",
    "Reply All": "پاسخ به همه",
    "Forward": "ارسال مجدد",
    "Message sent.": "پیام ارسال شد.",
    "Draft saved.": "پیش‌نویس ذخیره شد.",
    "Address Books": "دفترچه‌های نشانی",
    "Contacts": "مخاطبان",
    "New Folder": "پوشه جدید",
}
