*
!package.json
!yarn.lock
!pyproject.toml

!frontend/
frontend/*
!frontend/package.json

!e2e/
e2e/*
!e2e/package.json
!e2e/yarn.lock

!suite/
suite/*
!suite/meet/
suite/meet/*
!suite/meet/sfu-server/
suite/meet/sfu-server/*
!suite/meet/sfu-server/package.json
!suite/meet/sfu-server/yarn.lock
