import { MaybeRefOrGetter, toValue, ref } from 'vue'
import { useDoc, createResource } from 'frappe-ui'
import { prettyData } from '@/apps/drive/ui/drive/js/utils'
import { getDocuments } from '@/apps/writer/resources/'

const trackVisit = createResource({
  url: 'suite.drive.api.files.track_visit',
  makeParams: (entity_name: string) => ({ entity_name }),
})

export default function useDocument(docId: MaybeRefOrGetter<string>) {
  const name = toValue(docId)
  // Add autogenerated types
  const file = useDoc({
    doctype: 'File',
    name,
    url:
      '/api/method/suite.drive.api.permissions.get_entity_with_permissions?entity_name=' +
      name,
    transform: (doc) => {
      return prettyData(doc)
    },
    methods: {
      toggleFav: { name: 'toggle_favourite' },
    },
  })
  // Construct a fake useDoc until we fetch data
  const document = ref({ doc: null })
  file.onSuccess((doc) => {
    document.value = useDoc({
      doctype: 'Writer Document',
      name: doc.content_docname,
      transform(doc) {
        if (typeof doc.settings === 'string') doc.settings = JSON.parse(doc.settings)
        else if (!doc.settings) doc.settings = {}
        return doc
      },
      methods: {
        newVersion: 'new_version',
        saveDoc: 'save_doc',
        saveHtml: 'save_html',
        updateSettings: 'update_settings',
      },
    })
    trackVisit.submit(name)
    getDocuments.updateRow({
      name: docId,
      accessed: new Date().toISOString(),
    })
  })
  return { file, document }
}
