import { MaybeRefOrGetter, toValue, ref } from 'vue'
import { useDoc } from 'frappe-ui'
import { prettyData } from 'frappe-ui/drive/js/utils'
import { getDocuments } from '@/resources/'

export default function useDocument(docId: MaybeRefOrGetter<string>) {
  const name = toValue(docId)
  // Add autogenerated types
  const file = useDoc({
    doctype: 'Drive File',
    name,
    url: '/api/method/drive.api.permissions.get_entity_with_permissions?entity_name=' + name,
    transform: (doc) => {
      return prettyData(doc)
    },
    methods: {
      toggleFav: { name: 'toggle_favourite' },
    },
  })
  // Construct a fake useDoc until we fetch data
  const document = ref({ doc: null })
  file.onSuccess(() => {
    document.value = useDoc({
      doctype: 'Writer Document',
      name: file.doc.doc,
      transform(doc) {
        if (doc.settings) doc.settings = JSON.parse(doc.settings)
        if (doc.comments)
          doc.comments = doc.comments.map((k) => ({
            ...k,
            anchor: JSON.parse(k.anchor),
          }))
      },
      methods: {
        newVersion: 'new_version',
        saveDoc: 'save_doc',
        saveHtml: 'save_html',
        updateSettings: 'update_settings',
      },
    })
    getDocuments.updateRow({
      name: docId,
      accessed: new Date().toISOString(),
    })
  })
  return { file, document }
}
